#!/bin/bash

set -e

log_start() {
    echo -n "$@"
}

log_end() {
    [ $1 -eq 0 ] && echo -e "\033[1;32m[Done]\033[m" || echo -e "\033[1;31m[Failed]\033[m"
}


add_service () {
    log_start "Installing $1 service... "
    if `which systemctl 1>/dev/null 2>&1` ; then
        systemctl enable $1 1>/dev/null 2>&1
    else
        update-rc.d $1 defaults 1>/dev/null 2>&1
    fi

    log_end $?
}

del_service () {
    log_start "Removing $1 service... "
    if `which systemctl 1>/dev/null 2>&1` ; then
        systemctl disable $1 1>/dev/null 2>&1
    else
        update-rc.d -f $1 remove 1>/dev/null 2>&1
    fi

    log_end $?
}

export PACKSTAGE=$1
export ADDITIONAL_STAGE=$2

is_upgrade () {
    ([[ "$PACKSTAGE" == "configure" ]] || [[ "$PACKSTAGE" == "upgrade" ]]) && [[ -n "$ADDITIONAL_STAGE" ]]
}

if ! is_upgrade ; then
    add_service dkms-service
fi

if dpkg --compare-versions "$2" lt-nl "2.0.21.1-1~" ; then
    if [ -e "/etc/modprobe.d/dkms" ]; then
        md5sum=$(md5sum /etc/modprobe.d/dkms | sed -e 's/ .*//')
        old_md5sum=$(dpkg-query -W -f='${Conffiles}' dkms | \
            sed -n -e "\' /etc/modprobe.d/dkms ' { s/ obsolete$//; s/.* //; p }")
        if [ "$md5sum" = "$old_md5sum" ]; then
            rm -f /etc/modprobe.d/dkms
        else
            echo "Moving /etc/modprobe.d/dkms to /etc/modprobe.d/dkms.conf ..."
            mv /etc/modprobe.d/dkms /etc/modprobe.d/dkms.conf
            rm -f /etc/modprobe.d/dkms
        fi
    fi
fi

#DEBHELPER#
