#!/bin/bash

set -e

log_start() {
    echo -n "$@"
}

log_end() {
    [ $1 -eq 0 ] && echo -e "\033[1;32m[Done]\033[m" || echo -e "\033[1;31m[Failed]\033[m"
}


add_service () {
    log_start "Installing $1 service... "
    if `which systemctl 1>/dev/null 2>&1` ; then
        systemctl enable $1 1>/dev/null 2>&1
    else
        update-rc.d $1 defaults 1>/dev/null 2>&1
    fi

    log_end $?
}

del_service () {
    log_start "Removing $1 service... "
    if `which systemctl 1>/dev/null 2>&1` ; then
        systemctl disable $1 1>/dev/null 2>&1
    else
        update-rc.d -f $1 remove 1>/dev/null 2>&1
    fi

    log_end $?
}

# Remove a no-longer used conffile
rm_conffile() {
    PKGNAME="$1"
    CONFFILE="$2"
    if [ -e "$CONFFILE" ]; then
        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
        old_md5sum="`dpkg-query -W -f='${Conffiles}' $PKGNAME | sed -n -e \"\\\\' $CONFFILE '{s/ obsolete$//;s/.* //p}\"`"
        if [ "$md5sum" != "$old_md5sum" ]; then
            echo "Obsolete conffile $CONFFILE has been modified by you."
            echo "Saving as $CONFFILE.dpkg-bak ..."
            mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
        else
            echo "Removing obsolete conffile $CONFFILE ..."
            rm -f "$CONFFILE"
        fi
    fi
}

case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" le "2.1.1.1-2"; then
        rm_conffile dkms "/etc/dkms/template-dkms-mkdeb/debian/postrm"
    if [ -e "/etc/init.d/dkms_autoinstaller" ]; then
        del_service dkms_autoinstaller
        rm_conffile dkms "/etc/init.d/dkms_autoinstaller"
    fi
        rm_conffile dkms "/etc/init/dkms_autoinstaller.conf"
    fi

esac
