#!/bin/sh

#set -x

# chkconfig: 2345 98 02
# description: Compiles and install kernel modules automatically for new kernels at boot.

### BEGIN INIT INFO
# Provides: dkms_service dkms
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Required-Start: $local_fs
# Short-Description: DKMS kernel modules installer service
# Description: A service to automatically install DKMS modules for new kernels.
### END INIT INFO

case "$1" in
    start)
        /bin/sh -c '/usr/lib/dkms/dkms_autoinstaller $(uname -r)'
        ;;
    stop|restart|force-reload|status|reload)
        # There is no stop action, this and the 04 priority during stop is
        # added to make RHEL chkconfig happy.
        # Ignore others on debian/ubuntu too
        ;;
    *)
        echo $"Usage: $0 {start}"
        exit 2
esac
