#!/bin/sh

#set -x

if [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
elif [ -f /etc/rc.d/init.d/functions ]; then 
    . /etc/rc.d/init.d/functions
fi

#We only have these functions on debian/ubuntu
# so on other distros just stub them out
if [ ! -f /etc/debian_version ]; then
    alias log_daemon_msg=/bin/echo
    log_end_msg() { if [ "$1" = "0" ]; then echo " Done. "; else echo " Failed. "; fi }
    export -f log_end_msg
    alias log_action_begin_msg=log_daemon_msg
    alias log_action_end_msg=log_end_msg
fi

dkms="/usr/sbin/dkms"
dkms_name="dkms"

test -f $dkms ||
{
    echo "No DKMS executable was found. Skiping autoinstall for kernel $2."
    exit 0
}

[ -e /etc/sysconfig/$dkms_name ] && . /etc/sysconfig/$dkms_name

if [ -n "$1" ]; then
    kernel="$1"
else
    kernel=`uname -r`
fi

log_daemon_msg "$dkms_name: running auto installation service for kernel $kernel"
$dkms autoinstall --kernelver $kernel
log_end_msg $?
